// This should be on a .json
const verbs = [
    { word: 'abonnieren', translations: ['suscribir', 'abonar'] },
    { word: 'akzeptieren', translations: ['aceptar'] },
    { word: 'arbeiten', translations: ['trabajar'] },
    { word: 'benutzen', translations: ['usar', 'utilizar'] },
    { word: 'bestellen', translations: ['pedir'] },
    { word: 'bleiben', translations: ['quedarse', 'quedar'] },
    { word: 'der glaube', translations: ['la fe'] },
    { word: 'erkennen', translations: ['reconocer'] },
    { word: 'erlauben', translations: ['permitir'] },
    { word: 'ersetzen', translations: ['reemplazar', 'sustituir'] },
    { word: 'erweitern', translations: ['alargar', 'dilatar', 'ampliar', 'extender'] },
    { word: 'fahren', translations: ['viajar'] },
    { word: 'fehlen', translations: ['faltar', 'echar de menos'] },
    { word: 'finden', translations: ['encontrar'] },
    { word: 'funktionieren', translations: ['funcionar'] },
    { word: 'geben', translations: ['dar'] },
    { word: 'gefallen', translations: ['gustar'] },
    { word: 'glauben', translations: ['creer', 'opinar'] },
    { word: 'halten', translations: ['sostener', 'aguantar'] },
    { word: 'hoffen', translations: ['esperar', 'confiar'] },
    { word: 'hören', translations: ['oír', 'escuchar'] },
    { word: 'kochen', translations: ['cocinar'] },
    { word: 'kommen', translations: ['venir'] },
    { word: 'kosten', translations: ['costar', 'valer'] },
    { word: 'leben', translations: ['vivir'] },
    { word: 'liegen', translations: ['estar ubicado', 'estar tendido'] },
    { word: 'machen', translations: ['hacer'] },
    { word: 'meinen', translations: ['pensar', 'opinar'] },
    { word: 'mögen', translations: ['querer, gustar'] },
    { word: 'möchte', translations: ['querría'] },
    { word: 'nehmen', translations: ['tomar', 'coger'] },
    { word: 'passieren', translations: ['pasar', 'suceder', 'ocurrir'] },
    { word: 'prüfen', translations: ['revisar', 'controlar', 'probar'] },
    { word: 'reden', translations: ['hablar'] },
    { word: 'reisen', translations: ['viajar'] },
    { word: 'sammeln', translations: ['reunir', 'recoger', 'coleccionar'] },
    { word: 'scheinen', translations: ['brillar', 'parecer'] },
    { word: 'schließen', translations: ['cerrar'] },
    { word: 'schwimmen', translations: ['nadar'] },
    { word: 'singen', translations: ['cantar'] },
    { word: 'spazieren', translations: ['pasear'] },
    { word: 'stehlen', translations: ['robar'] },
    { word: 'stellen', translations: ['poner', 'colocar'] },
    { word: 'subskribieren', translations: ['suscribirse'] },
    { word: 'suchen', translations: ['buscar', 'rastrear'] },
    { word: 'treffen', translations: ['encontrar'] },
    { word: 'verbrauchen', translations: ['consumir'] },
    { word: 'verkaufen', translations: ['vender'] },
    { word: 'warten', translations: ['esperar'] },
    { word: 'wohnen', translations: ['vivir'] },
    { word: 'zeigen', translations: ['enseñar', 'mostrar', 'transmitir'] },
    { word: 'ändern', translations: ['cambiar', 'modificar'] },
    { word: 'übernehmen', translations: ['hacerse cargo de', 'tomar las riendas'] }
]

const separableVerbs = [
    { word: 'anhalten', translations: ['detener', 'parar'] },
    { word: 'anmachen', translations: ['encender'] },
    { word: 'aufhalten', translations: ['retener'] },
    { word: 'aufhören', translations: ['detener', 'terminar', 'acabar'] },
    { word: 'aufmachen', translations: ['abrir'] },
    { word: 'aufräumen', translations: ['limpiar'] },
    { word: 'aufstehen', translations: ['levantarse'] },
    { word: 'aufsteigen', translations: ['subir', 'montar'] },
    { word: 'ausgehen', translations: ['salir'] },
    { word: 'aussehen', translations: ['parecer'] },
    { word: 'aussteigen', translations: ['bajar', 'salir'] },
    { word: 'einsammeln', translations: ['recoger'] },
    { word: 'eintreffen', translations: ['llegar'] },
    { word: 'festhalten', translations: ['agarrar', 'detener'] },
    { word: 'hören auf', translations: ['hacer caso'] },
    { word: 'untergehen', translations: ['hundirse'] },
    { word: 'vorstellen', translations: ['presentar'] },
    { word: 'zumachen', translations: ['cerrar'] }
]

const predicativeAdjectives = [
    { word: 'abhängig', translations: ['adicto', 'dependiente'] },
    { word: 'aktiv', translations: ['activo'] },
    { word: 'allgemein', translations: ['general/mente', 'común'] },
    { word: 'ausgezeichnet', translations: ['excelente', 'magnífico'] },
    { word: 'automatisch', translations: ['automático'] },
    { word: 'begeister', translations: ['entusiasmado', 'impresionado'] },
    { word: 'beliebt', translations: ['apreciada', 'popular'] },
    { word: 'bereit', translations: ['listos'] },
    { word: 'deutlich', translations: ['claro', 'claramente'] },
    { word: 'echt', translations: ['de verdad', 'real', 'auténtico'] },
    { word: 'egal', translations: ['da lo mismo', 'igual', 'no importa'] },
    { word: 'eindeutig', translations: ['obvio', 'inequívoco', 'indiscutible', 'indudable'] },
    { word: 'erneut', translations: ['nuevo'] },
    { word: 'extrem', translations: ['extremadamente', 'extremo'] },
    { word: 'falsch', translations: ['malo', 'falso'] },
    { word: 'fertig', translations: ['cansado', 'rendido'] },
    { word: 'fit', translations: ['en forma'] },
    { word: 'herzlich', translations: ['cordial', 'afectuosa', 'cariñosa'] },
    { word: 'hilfreich', translations: ['útil', 'beneficioso'] },
    { word: 'höher', translations: ['más alto'] },
    { word: 'individuell', translations: ['individual'] },
    { word: 'international', translations: ['internacional'] },
    { word: 'jung', translations: ['joven'] },
    { word: 'jährlich', translations: ['anualmente', 'al año'] },
    { word: 'kaputt', translations: ['roto', 'estropeado'] },
    { word: 'knapp', translations: ['escasa', 'justa'] },
    { word: 'komplett', translations: ['completamente'] },
    { word: 'kürzlich', translations: ['recientemente', 'hace poco'] },
    { word: 'leicht', translations: ['ligero'] },
    { word: 'leichter', translations: ['más fácil', 'más liviano', 'más ligero'] },
    { word: 'länger', translations: ['más largo'] },
    { word: 'müde', translations: ['cansado'] },
    { word: 'notwendig', translations: ['necesaria'] },
    { word: 'offen', translations: ['abierto'] },
    { word: 'original', translations: ['original'] },
    { word: 'persönlich', translations: ['personal'] },
    { word: 'plötzlich', translations: ['de pronto', 'repentino'] },
    { word: 'privat', translations: ['en privado'] },
    { word: 'regional', translations: ['regional', 'local'] },
    { word: 'relativ', translations: ['relativo'] },
    { word: 'ruhig', translations: ['tranquilo'] },
    { word: 'schöner', translations: ['más bonito'] },
    { word: 'selbst', translations: ['por sí mismo'] },
    { word: 'selbstverständlich', translations: ['evidente', 'lógico', 'obvio'] },
    { word: 'sichtvar', translations: ['visible'] },
    { word: 'sinnvoll', translations: ['sensato'] },
    { word: 'stärker', translations: ['más fuertes'] },
    { word: 'tatsächlich', translations: ['efectivamente'] },
    { word: 'täglich', translations: ['diariamente', 'a diario'] },
    { word: 'unabhängig', translations: ['independiente'] },
    { word: 'unbekannt', translations: ['desconocido'] },
    { word: 'verantwortlich, zuständig', translations: ['responsable'] },
    { word: 'verfügbar', translations: ['disponible'] },
    { word: 'verpflichtet', translations: ['comprometido', 'obligado'] },
    { word: 'verständ', translations: ['comprensible'] },
    { word: 'völlig', translations: ['todo'] },
    { word: 'wert', translations: ['vale'] },
    { word: 'wesentlich', translations: ['esencial', 'fundamental'] },
    { word: 'wirklich', translations: ['de verdad', 'realmente'] },
    { word: 'zufrieden', translations: ['contento', 'satisfecho'] },
    { word: 'ähnlich', translations: ['similar', 'parecida', 'semejante'] }
]

const medicine = [
    { word: 'das auge', translations: ['el ojo'] },
    { word: 'das bein', translations: ['la pierna'] },
    { word: 'das blut', translations: ['la sangre'] },
    { word: 'das formular', translations: ['el formulario'] },
    { word: 'das gesicht', translations: ['la cara'] },
    { word: 'das haar', translations: ['el pelo'] },
    { word: 'das herz', translations: ['el corazón'] },
    { word: 'das krankenhaus', translations: ['el hospital'] },
    { word: 'das medikament', translations: ['el medicamento'] },
    { word: 'das opfer', translations: ['la víctima'] },
    { word: 'der Fuß', translations: ['el pie'] },
    { word: 'der alkohol', translations: ['el alcohol'] },
    { word: 'der finger', translations: ['el dedo'] },
    { word: 'der hals', translations: ['el cuello'] },
    { word: 'der kopf', translations: ['la cabeza'] },
    { word: 'der krankenwagen', translations: ['la ambulancia'] },
    { word: 'der körper', translations: ['el cuerpo'] },
    { word: 'der notfall', translations: ['la emergencia'] },
    { word: 'der patient', translations: ['el paciente'] },
    { word: 'der unfall', translations: ['el accidente'] },
    { word: 'die beine', translations: ['las piernas'] },
    { word: 'die diät', translations: ['la dieta'] },
    { word: 'die ernährung', translations: ['la alimentación'] },
    { word: 'die füße', translations: ['los pies'] },
    { word: 'die geburt', translations: ['el nacimiento', 'parto'] },
    { word: 'die gesundheit', translations: ['la salud'] },
    { word: 'die haare', translations: ['el pelo'] },
    { word: 'die hand', translations: ['la mano'] },
    { word: 'die haut', translations: ['la piel'] },
    { word: 'die klinik', translations: ['la clínica'] },
    { word: 'die krankenversicherung', translations: ['el seguro de enfermedad'] },
    { word: 'die krankheit', translations: ['la enfermedad'] },
    { word: 'die medizin', translations: ['la medicina'] },
    { word: 'die pflege', translations: ['el cuidado', 'la asistencia'] },
    { word: 'die praxis', translations: ['el consultorio'] },
    { word: 'die sucht', translations: ['la adicción'] },
    { word: 'die therapie', translations: ['la terapia'] },
    { word: 'die untersuchung', translations: ['el examen', 'análisis', 'chequeo'] },
    { word: 'krank', translations: ['enfermo'] }
]

const newPalabros = [
    { word: 'apotheke', translations: ['farmacia'] },
    { word: 'auch', translations: ['también'] },
    { word: 'computer', translations: ['computadora'] },
    { word: 'da', translations: ['allí'] },
    { word: 'das fenster ist auf', translations: ['la ventana está abierta'] },
    { word: 'das fußballspieler', translations: ['el futbolista'] },
    { word: 'das meer', translations: ['el océano'] },
    { word: 'das mädchen ist draußen', translations: ['la niña está fuera'] },
    { word: 'das problem', translations: ['el problema'] },
    { word: 'das wetter', translations: ['el tiempo'] },
    { word: 'der aufzug ist da vorne', translations: ['el ascensor está ahí enfrente'] },
    { word: 'der berg', translations: ['la montaña'] },
    { word: 'der druck', translations: ['la presión'] },
    { word: 'der junge ist drinnen', translations: ['el niño está dentro'] },
    { word: 'der karton ist leer', translations: ['la caja está vacía'] },
    { word: 'der külhschrank', translations: ['el frigorífico'] },
    { word: 'der politiker', translations: ['el político'] },
    { word: 'der preis', translations: ['el precio'] },
    { word: 'der schrank', translations: ['el armario'] },
    { word: 'der sommer', translations: ['el verano'] },
    { word: 'der sport', translations: ['el deporte'] },
    { word: 'die bäckerei', translations: ['la panadería'] },
    { word: 'die freiheit', translations: ['la libertad'] },
    { word: 'die kinder sind weg', translations: ['los niños se han ido'] },
    { word: 'die lampe ist aus', translations: ['la lámpara está apagada'] },
    { word: 'die nachrichten', translations: ['las noticias'] },
    { word: 'die prüfung', translations: ['el examen'] },
    { word: 'die ratte', translations: ['la rata'] },
    { word: 'die sprache', translations: ['el lenguaje'] },
    { word: 'die treppe ist da hinten', translations: ['las escaleras están allí detrás'] },
    { word: 'die tür ist zu', translations: ['la puerta está cerrada'] },
    { word: 'die wahrheit', translations: ['la verdad'] },
    { word: 'dort', translations: ['allí'] },
    { word: 'draußen', translations: ['fuera'] },
    { word: 'er lernt viel', translations: ['él estudia mucho'] },
    { word: 'erklären', translations: ['explicar'] },
    { word: 'erwarten', translations: ['esperar'] },
    { word: 'gefährlich', translations: ['peligroso'] },
    { word: 'gerade', translations: ['ahora'] },
    { word: 'geradeus', translations: ['recto'] },
    { word: 'guten abend', translations: ['buenas tardes'] },
    { word: 'guten morgen', translations: ['buenos días'] },
    { word: 'guten tag', translations: ['buen día'] },
    { word: 'hier', translations: ['aquí'] },
    { word: 'ich heiße', translations: ['me llamo'] },
    { word: 'ich komme aus', translations: ['vengo de'] },
    { word: 'ich wohne in', translations: ['vivo en'] },
    { word: 'kritisieren', translations: ['criticar'] },
    { word: 'lernen', translations: ['estudiar', 'aprender'] },
    { word: 'lärm', translations: ['ruido'] },
    { word: 'oben', translations: ['arriba'] },
    { word: 'pause', translations: ['descanso'] },
    { word: 'prima', translations: ['bien'] },
    { word: 'rechts', translations: ['derechos'] },
    { word: 'schreien', translations: ['gritar'] },
    { word: 'studieren', translations: ['estudiar'] },
    { word: 'unten', translations: ['debajo'] },
    { word: 'verlieren', translations: ['perder'] },
    { word: 'vielleicht', translations: ['quizás'] },
    { word: 'wie heißen sie?', translations: ['cómo se llama? formal'] },
    { word: 'wie heißt du?', translations: ['cómo te llamas? informal'] },
    { word: 'wie heißt ihr?', translations: ['cómo os llamais? informal'] },
    { word: 'wie ist dein name?', translations: ['cuál es tu nombre? informal'] },
    { word: 'wie ist ihr name?', translations: ['cuál es su nombre? formal'] },
    { word: 'überstunden', translations: ['horas extra'] }
]

const feelings = [
    { word: 'das glück', translations: ['la suerte'] },
    { word: 'das verständnis', translations: ['el entendimiento'] },
    { word: 'der Spaß', translations: ['la diversión'] },
    { word: 'der eindruck', translations: ['la impresión'] },
    { word: 'der gedanke', translations: ['el pensamiento', 'idea'] },
    { word: 'der humor', translations: ['el humor'] },
    { word: 'der traum', translations: ['el sueño'] },
    { word: 'der wunsch', translations: ['el deseo'] },
    { word: 'die angst', translations: ['el miedo'] },
    { word: 'die freude', translations: ['la alegría'] },
    { word: 'die idee', translations: ['la idea'] },
    { word: 'die liebe', translations: ['el amor'] },
    { word: 'die lust', translations: ['las ganas'] },
    { word: 'die not', translations: ['la necesidad'] },
    { word: 'die ruhe', translations: ['la calma', 'tranquilidad', 'silencio'] },
    { word: 'die wünsche', translations: ['los deseos'] },
    { word: 'es ist mein Ernst', translations: ['lo digo en serio'] },
    { word: 'im ernst?', translations: ['en serio?'] },
    { word: 'träumen', translations: ['soñar'] },
    { word: 'unheimlich', translations: ['tenebroso', 'inquietante'] },
    { word: 'witzig', translations: ['gracioso'] }
]

const dates = [
    { word: 'Weihnachten steht vor der Tür', translations: ['la navidad está a punto de llegar'] },
    { word: 'alter', translations: ['edad', 'vejez'] },
    { word: 'das 18. jahrhundert', translations: ['el siglo XVIII'] },
    { word: 'das datum', translations: ['la fecha'] },
    { word: 'das ende', translations: ['el fin'] },
    { word: 'das quartal', translations: ['el trimestre'] },
    { word: 'das weihnachten', translations: ['la navidad'] },
    { word: 'das wochenende', translations: ['el fin de semana'] },
    { word: 'der abend', translations: ['la tarde'] },
    { word: 'der alltag', translations: ['la vida cotidiana', 'el día a día', 'la rutina'] },
    { word: 'der geburtstag', translations: ['el cumpleaños'] },
    { word: 'der kalender', translations: ['el calendario'] },
    { word: 'der mittag', translations: ['el mediodía'] },
    { word: 'der moment', translations: ['el momento'] },
    { word: 'der monat', translations: ['el mes'] },
    { word: 'der morgen', translations: ['la mañana'] },
    { word: 'der termin', translations: ['el plazo', 'la fecha', 'la cita'] },
    { word: 'der zeitpunkt', translations: ['el momento'] },
    { word: 'der zeitraum', translations: ['el periodo'] },
    { word: 'die dauer', translations: ['la duración'] },
    { word: 'die letzte', translations: ['el último'] },
    { word: 'die minute', translations: ['el minuto'] },
    { word: 'die nacht', translations: ['la noche'] },
    { word: 'die phase', translations: ['la fase', 'la etapa'] },
    { word: 'die saison', translations: ['la temporada'] },
    { word: 'die sekunde', translations: ['el segundo'] },
    { word: 'die stunde', translations: ['la hora'] },
    { word: 'die uhr', translations: ['la hora', 'el reloj'] },
    { word: 'die uhrzeit', translations: ['la hora'] },
    { word: 'die vergangenheit', translations: ['el pasado'] },
    { word: 'die woche', translations: ['la semana'] },
    { word: 'die zeit', translations: ['el tiempo'] },
    { word: 'die zukunft', translations: ['el futuro'] },
    { word: 'im moment', translations: ['de momento'] },
    { word: 'jahrhundert', translations: ['siglo'] },
    { word: 'monate', translations: ['meses'] },
    { word: 'urlaub', translations: ['vacaciones'] },
    { word: 'wochen', translations: ['semanas'] }
]

const weekDays = [
    { word: 'montag', translations: ['lunes'] },
    { word: 'dienstag', translations: ['martes'] },
    { word: 'mittwoch', translations: ['miércoles'] },
    { word: 'donnerstag', translations: ['jueves'] },
    { word: 'freitag', translations: ['viernes'] },
    { word: 'samstag', translations: ['sábado'] },
    { word: 'sonntag', translations: ['domingo'] }
]

const months = [
    { word: 'der Januar', translations: ['enero'] },
    { word: 'der Februar', translations: ['febrero'] },
    { word: 'der März', translations: ['marzo'] },
    { word: 'der April', translations: ['abril'] },
    { word: 'der Mai', translations: ['mayo'] },
    { word: 'der Juni', translations: ['junio'] },
    { word: 'der Juli', translations: ['julio'] },
    { word: 'der August', translations: ['agosto'] },
    { word: 'der September', translations: ['septiembre'] },
    { word: 'der Oktober', translations: ['octubre'] },
    { word: 'der November', translations: ['noviembre'] },
    { word: 'der Dezember', translations: ['diciembre'] },
    { word: 'im mes', translations: ['en mes'] }
]

const seasons = [
    { word: 'der Frühling', translations: ['la primavera'] },
    { word: 'der Sommer', translations: ['el verano'] },
    { word: 'der Herbst', translations: ['el otoño'] },
    { word: 'der Winter', translations: ['el invierno'] }
]

const adverbs = [
    { word: 'allein', translations: ['solo', 'únicamente'] },
    { word: 'auch nicht', translations: ['tampoco'] },
    { word: 'auch', translations: ['también', 'incluso', 'incluyendo'] },
    { word: 'außerdem', translations: ['además', 'aparte'] },
    { word: 'bereits', translations: ['ya'] },
    { word: 'besonders', translations: ['particularmente', 'especialmente'] },
    { word: 'dabei', translations: ['conmigo', 'incluido', 'al mismo tiempo'] },
    { word: 'daher', translations: ['de ahí', 'por eso'] },
    { word: 'damit', translations: ['con ello/esto/eso'] },
    { word: 'danach', translations: ['después', 'más tarde', 'a continuación'] },
    { word: 'dann', translations: ['luego', 'más tarde', 'entonces'] },
    { word: 'darüber', translations: ['de arriba', 'en esto', 'sobre esto'] },
    { word: 'dazu', translations: ['a esto', 'para esto', 'para eso'] },
    { word: 'dennoch', translations: ['a pesar de todo', 'no obstante'] },
    { word: 'dort', translations: ['allí'] },
    { word: 'durchaus', translations: ['absolutamente', 'definitivamente'] },
    { word: 'einmal', translations: ['una vez', 'antes', 'un día'] },
    { word: 'etwa', translations: ['por ejemplo', 'aproximadamente', 'más o menos'] },
    { word: 'fast', translations: ['casi', 'prácticamente'] },
    { word: 'genauso', translations: ['de igual modo', 'de la misma manera', 'tan'] },
    { word: 'gerne', translations: ['con gusto'] },
    { word: 'gestern', translations: ['ayer'] },
    { word: 'heute', translations: ['hoy'] },
    { word: 'hier', translations: ['aquí'] },
    { word: 'hingegen', translations: ['por el contrario', 'en cambio'] },
    { word: 'ich bin damit durch', translations: ['he terminado con esto'] },
    { word: 'immer noch', translations: ['aún'] },
    { word: 'immer', translations: ['siempre'] },
    { word: 'innen', translations: ['dentro', 'en el interior'] },
    { word: 'jedenfalls', translations: ['en todo caso', 'sea como sea'] },
    { word: 'jedoch', translations: ['pero', 'sin embargo'] },
    { word: 'jetzt', translations: ['ahora'] },
    { word: 'kaum', translations: ['apenas'] },
    { word: 'meistens', translations: ['la mayoría de las veces', 'por lo general'] },
    { word: 'mindestens', translations: ['por lo menos', 'como mínimo'] },
    { word: 'noch einmal', translations: ['otra vez'] },
    { word: 'noch eins bitte', translations: ['otro más por favor'] },
    { word: 'noch', translations: ['aún', 'todavía', 'más'] },
    { word: 'nun', translations: ['ahora', 'pues', 'ahora bien'] },
    { word: 'nur', translations: ['sólo'] },
    { word: 'oben', translations: ['arriba'] },
    { word: 'schon', translations: ['ya'] },
    { word: 'selbe/er/es', translations: ['mismo'] },
    { word: 'selbst', translations: ['incluso', 'hasta'] },
    { word: 'so viele', translations: ['tantos'] },
    { word: 'so', translations: ['así', 'de esta manera', 'tan'] },
    { word: 'sofort', translations: ['ahora mismo', 'enseguida', 'inmediato'] },
    { word: 'somit', translations: ['por lo tanto', 'por consiguiente'] },
    { word: 'sonst', translations: ['por lo demás', 'más', 'normalmente', 'siempre', 'antes', 'si no'] },
    { word: 'spätestens', translations: ['como muy tarde', 'lo más tarde'] },
    { word: 'weder ... noch ...', translations: ['ni ... ni ...'] },
    { word: 'weg', translations: ['desparecido', 'ausente', 'perdido'] },
    { word: 'wieder', translations: ['otra vez', 'de nuevo'] },
    { word: 'zuerst', translations: ['primero', 'en primer lugar'] },
    { word: 'zuletzt', translations: ['al final', 'finalmente'] },
    { word: 'überhaupt nicht', translations: ['en absoluto'] },
    { word: 'überhaupt', translations: ['en general', 'en realidad', 'a fin de cuentas'] }
]

const nature = [
    { word: 'das all', translations: ['el universo', 'el cosmos'] },
    { word: 'das feuer', translations: ['el fuego'] },
    { word: 'das gold', translations: ['el oro'] },
    { word: 'das gras', translations: ['la hierba'] },
    { word: 'das holz', translations: ['la madera'] },
    { word: 'das klima', translations: ['el clima'] },
    { word: 'das meer', translations: ['el mar'] },
    { word: 'das metall', translations: ['el metal'] },
    { word: 'das wetter', translations: ['el tiempo'] },
    { word: 'der baum', translations: ['el árbol'] },
    { word: 'der berg', translations: ['el monte', 'la montaña'] },
    { word: 'der garten', translations: ['el jardín'] },
    { word: 'der himmel', translations: ['el cielo'] },
    { word: 'der mond', translations: ['la luna'] },
    { word: 'der ozean', translations: ['el océano'] },
    { word: 'der regen', translations: ['la lluvia'] },
    { word: 'der rhein', translations: ['el rin'] },
    { word: 'der see', translations: ['el lago'] },
    { word: 'der stahl', translations: ['el acero'] },
    { word: 'der stein', translations: ['la piedra'] },
    { word: 'der stern', translations: ['la estrella'] },
    { word: 'der strand', translations: ['la playa'] },
    { word: 'der strom', translations: ['la energía', 'la corriente'] },
    { word: 'der wald', translations: ['el bosque'] },
    { word: 'der wind', translations: ['el viento'] },
    { word: 'die atmosphäre', translations: ['la atmósfera'] },
    { word: 'die blume', translations: ['la flor'] },
    { word: 'die bäume', translations: ['los árboles'] },
    { word: 'die chemie', translations: ['la química'] },
    { word: 'die erde', translations: ['la tierra'] },
    { word: 'die luft', translations: ['el aire'] },
    { word: 'die natur', translations: ['la naturaleza'] },
    { word: 'die pflanze', translations: ['la planta'] },
    { word: 'die see', translations: ['el mar'] },
    { word: 'die sonne', translations: ['el sol'] },
    { word: 'die tierwelt', translations: ['la fauna'] },
    { word: 'die umwelt', translations: ['el medio ambiente'] },
    { word: 'die welt', translations: ['la tierra', 'el mundo'] },
    { word: 'die wiese', translations: ['la pradera'] },
    { word: 'zunehmen', translations: ['aumentar', 'intensificarse'] }
]

const verbs2 = [
    { word: 'aussagen', translations: ['declarar'] },
    { word: 'bestätigen', translations: ['confirmar', 'certificar'] },
    { word: 'betrachten', translations: ['ver', 'mirar', 'contemplar'] },
    { word: 'dass', translations: ['que'] },
    { word: 'entscheiden', translations: ['decidir', 'resolver'] },
    { word: 'formen', translations: ['formar'] },
    { word: 'fragen', translations: ['preguntar'] },
    { word: 'mieten', translations: ['alquilar'] },
    { word: 'mitmachen', translations: ['participar'] },
    { word: 'nehmen wir an', translations: ['damos por hecho'] },
    { word: 'registrieren', translations: ['registrar', 'inscribir', 'anotar'] },
    { word: 'sagen', translations: ['decir'] },
    { word: 'teilnehmen', translations: ['participar'] },
    { word: 'tun', translations: ['hacer', 'actuar'] },
    { word: 'wecken', translations: ['despertar'] },
    { word: 'wiederholen', translations: ['repetir', 'repasar'] },
    { word: 'öffnen', translations: ['abrir'] }
]

const frequency = [
    { word: 'Mal', translations: ['vez'] },
    { word: 'als', translations: ['que'] },
    { word: 'bisschen', translations: ['poco'] },
    { word: 'größeres', translations: ['mayor', 'más grande'] },
    { word: 'häufig', translations: ['a menudo', 'frecuentemente'] },
    { word: 'keinerlei', translations: ['ningún'] },
    { word: 'manchmal', translations: ['a veces'] },
    { word: 'mehr', translations: ['más'] },
    { word: 'meist', translations: ['generalmente', 'muchas veces'] },
    { word: 'ob', translations: ['si'] },
    { word: 'oft', translations: ['a menudo', 'frecuentemente'] },
    { word: 'selten', translations: ['pocas veces', 'raramente'] },
    { word: 'sondern', translations: ['sino'] },
    { word: 'sowohl', translations: ['tanto', 'tan'] },
    { word: 'wenig', translations: ['poco'] },
    { word: 'weniger', translations: ['menos'] },
    { word: 'zahlreiche', translations: ['muchos/as'] }
]

const domestic = [
    { word: 'bad', translations: ['baño'] },
    { word: 'balkon', translations: ['balcón'] },
    { word: 'batterie', translations: ['batería'] },
    { word: 'bau', translations: ['construcción'] },
    { word: 'bett', translations: ['cama'] },
    { word: 'bettbezug', translations: ['ropa de cama'] },
    { word: 'dach', translations: ['techo'] },
    { word: 'fenster', translations: ['ventana'] },
    { word: 'flasche', translations: ['botella'] },
    { word: 'gabel', translations: ['tenedor'] },
    { word: 'gerät', translations: ['aparato'] },
    { word: 'glas', translations: ['vaso'] },
    { word: 'haushalt', translations: ['hogar'] },
    { word: 'haushaltsgeräte', translations: ['electrodomésticos'] },
    { word: 'heizung', translations: ['calefacción'] },
    { word: 'keller', translations: ['sótano'] },
    { word: 'küche', translations: ['cocina'] },
    { word: 'lampe', translations: ['lámpara'] },
    { word: 'leiter', translations: ['escalera'] },
    { word: 'licht', translations: ['luz'] },
    { word: 'löffel', translations: ['cuchara'] },
    { word: 'möbel', translations: ['muebles'] },
    { word: 'rasierer', translations: ['máquina de afeitar'] },
    { word: 'regenschirm', translations: ['paraguas'] },
    { word: 'reinigung', translations: ['limpieza'] },
    { word: 'schlafzimmer', translations: ['dormitorio'] },
    { word: 'schlüssel', translations: ['llave'] },
    { word: 'schüssel', translations: ['cuenco'] },
    { word: 'seife', translations: ['jabón'] },
    { word: 'spiegel', translations: ['espejo'] },
    { word: 'spielzeug', translations: ['juguete'] },
    { word: 'stuhl', translations: ['silla'] },
    { word: 'tasse', translations: ['taza'] },
    { word: 'teller', translations: ['plato'] },
    { word: 'tisch', translations: ['mesa'] },
    { word: 'toilette', translations: ['baño'] },
    { word: 'tor', translations: ['portón'] },
    { word: 'treppe', translations: ['escalera'] },
    { word: 'tür', translations: ['puerta'] },
    { word: 'umzug', translations: ['mudanza'] },
    { word: 'wand', translations: ['pared'] },
    { word: 'werkzeug', translations: ['herramienta'] },
    { word: 'wohnort', translations: ['lugar de residencia'] },
    { word: 'wohnung', translations: ['apartamento'] },
    { word: 'zahnbürste', translations: ['cepillo de dientes'] },
    { word: 'zahnpasta', translations: ['pasta de dientes'] },
    { word: 'öl', translations: ['aceite'] }
]

const variety = [
    { word: 'aber', translations: ['pero'] },
    { word: 'alle', translations: ['todos'] },
    { word: 'am', translations: ['en la', 'en el'] },
    { word: 'auf', translations: ['en'] },
    { word: 'aus', translations: ['de', 'desde', 'por'] },
    { word: 'bei uns', translations: ['a nuestra casa'] },
    { word: 'bei', translations: ['junto', 'cerca'] },
    { word: 'beide', translations: ['ambos'] },
    { word: 'beim', translations: ['en la', 'donde'] },
    { word: 'bessere', translations: ['el mejor'] },
    { word: 'beste', translations: ['mejor'] },
    { word: 'da', translations: ['aquí', 'ahí'] },
    { word: 'doch', translations: ['si', 'pero'] },
    { word: 'eher', translations: ['mas bien'] },
    { word: 'entweder', translations: ['o'] },
    { word: 'ganz', translations: ['del todo', 'totalmente', 'completamente'] },
    { word: 'gewöhnlich', translations: ['siempre', 'usualmente', 'común'] },
    { word: 'gute', translations: ['bueno'] },
    { word: 'hinter', translations: ['detrás'] },
    { word: 'jede', translations: ['todo'] },
    { word: 'jemand', translations: ['alguien'] },
    { word: 'man', translations: ['se'] },
    { word: 'manche', translations: ['algunos'] },
    { word: 'mit', translations: ['con'] },
    { word: 'nachdem', translations: ['después'] },
    { word: 'niemand', translations: ['nadie'] },
    { word: 'obwohl', translations: ['aunque'] },
    { word: 'oder', translations: ['o'] },
    { word: 'sehr', translations: ['muy', 'mucho'] },
    { word: 'sobald', translations: ['tan pronto como', 'en cuanto'] },
    { word: 'sofern', translations: ['siempre y cuando'] },
    { word: 'solange', translations: ['mientras'] },
    { word: 'sowie', translations: ['tanto... como...', 'así como', 'además de'] },
    { word: 'super', translations: ['genial', 'fantástico', 'estupendo'] },
    { word: 'und', translations: ['y'] },
    { word: 'viele', translations: ['muchos'] },
    { word: 'welches', translations: ['cual', 'que'] },
    { word: 'wenn', translations: ['cuando'] },
    { word: 'wie', translations: ['que', 'cuán', 'cómo'] },
    { word: 'ziemlich', translations: ['bastante'] },
    { word: 'zu(adverbio)', translations: ['muy', 'demasiado'] },
    { word: 'zu(preposición)', translations: ['con', 'en', 'a'] },
    { word: 'zum', translations: ['a la', 'al', 'hacia el'] },
    { word: 'zur', translations: ['al', 'a la'] }
]

const prepositions = [
    { word: 'ab und zu', translations: ['de vez en cuando'] },
    { word: 'ab', translations: ['desde', 'a partir de'] },
    { word: 'an', translations: ['encendida', 'de'] },
    { word: 'außer', translations: ['menos', 'excepto', 'a excepción de'] },
    { word: 'bis', translations: ['hasta'] },
    { word: 'durch', translations: ['a través', 'por'] },
    { word: 'einschließlich', translations: ['incluido', 'inclusive', 'incluyendo'] },
    { word: 'extra', translations: ['expresamente', 'especialmente', 'extra'] },
    { word: 'für', translations: ['para'] },
    { word: 'gegen', translations: ['contra'] },
    { word: 'gegenüber', translations: ['delante de', 'enfrente de', 'enfrente'] },
    { word: 'hinter', translations: ['detrás de', 'tras', 'detrás'] },
    { word: 'im (in dem)', translations: ['en el'] },
    { word: 'in', translations: ['en'] },
    { word: 'ins (in das)', translations: ['a la'] },
    { word: 'neben', translations: ['junto', 'al lado'] },
    { word: 'ohne', translations: ['sin'] },
    { word: 'seit', translations: ['desde'] },
    { word: 'trotz', translations: ['a pesar de'] },
    { word: 'um', translations: ['a las      mein flug ist um sechs'] },
    { word: 'ums (um das)', translations: ['alrededor', 'en torno a'] },
    { word: 'unter', translations: ['debajo de', 'entre'] },
    { word: 'vom (von + dem)', translations: ['del'] },
    { word: 'von', translations: ['de'] },
    { word: 'vor', translations: ['delante de', 'hace', 'antes de'] },
    { word: 'vorm (vor + dem)', translations: ['por delante de la'] },
    { word: 'wegen', translations: ['a causa de', 'debido a', 'por causa'] },
    { word: 'während', translations: ['durante', 'mientras'] },
    { word: 'zwischen', translations: ['entre'] },
    { word: 'über', translations: ['acerca de', 'sobre', 'de'] }
]

const professions = [
    { word: 'anwalt', translations: ['defensa'] },
    { word: 'arbeit', translations: ['empleo'] },
    { word: 'arbeitgeber/in', translations: ['empleador/a'] },
    { word: 'arbeitnehmer', translations: ['trabajador'] },
    { word: 'architekt', translations: ['arquitecto'] },
    { word: 'arzt', translations: ['doctor'] },
    { word: 'autor', translations: ['autor'] },
    { word: 'bauer', translations: ['agricultor'] },
    { word: 'bedienung', translations: ['servicio'] },
    { word: 'betreiber', translations: ['operador'] },
    { word: 'bürgermeister', translations: ['alcalde'] },
    { word: 'empfänger', translations: ['destinatario'] },
    { word: 'entwickler', translations: ['desarrollador'] },
    { word: 'expert', translations: ['experto'] },
    { word: 'fahrer', translations: ['conductor'] },
    { word: 'feuer', translations: ['fuego'] },
    { word: 'feuerwehr', translations: ['cuerpo de bomberos'] },
    { word: 'feuerwehrmann', translations: ['bombero'] },
    { word: 'führer', translations: ['líder'] },
    { word: 'geber', translations: ['dador'] },
    { word: 'geschäft', translations: ['negocio'] },
    { word: 'geschäftsführer', translations: ['gerente'] },
    { word: 'handwerk', translations: ['artesanía'] },
    { word: 'hersteller', translations: ['productor', 'fabricante'] },
    { word: 'händler', translations: ['comerciante', 'vendedor'] },
    { word: 'koch', translations: ['cocinero'] },
    { word: 'lehrer', translations: ['maestro'] },
    { word: 'lehrerin', translations: ['maestra'] },
    { word: 'leiter/in', translations: ['jefe/a'] },
    { word: 'meister', translations: ['maestro'] },
    { word: 'mitarbeiter', translations: ['trabajador'] },
    { word: 'nehmer', translations: ['tomador'] },
    { word: 'professor', translations: ['profesor'] },
    { word: 'recht', translations: ['derecho'] },
    { word: 'rechtsanwalt', translations: ['abogado'] },
    { word: 'reiseführer', translations: ['guía turístico'] },
    { word: 'richter', translations: ['juez'] },
    { word: 'schneider', translations: ['sastre'] },
    { word: 'schüler', translations: ['alumno'] },
    { word: 'schülerin', translations: ['alumna'] },
    { word: 'senior', translations: ['anciano'] },
    { word: 'spezialität', translations: ['especialidad'] },
    { word: 'student/in', translations: ['estudiante'] },
    { word: 'teil', translations: ['parte'] },
    { word: 'teilnehmer', translations: ['participante'] },
    { word: 'trainer', translations: ['entrenador'] },
    { word: 'verfasser', translations: ['autor'] },
    { word: 'verkäufer', translations: ['vendedor'] },
    { word: 'was meinen', translations: ['qué opinan'] },
    { word: 'weber', translations: ['tejedor'] },
    { word: 'wehr', translations: ['resistencia'] },
    { word: 'werkstatt', translations: ['taller'] },
    { word: 'ärtzin', translations: ['doctora'] }
]

const alphabet = [
    { word: 'A', translations: ['A'] },
    { word: 'B', translations: ['B'] },
    { word: 'C', translations: ['Se'] },
    { word: 'D', translations: ['D'] },
    { word: 'E', translations: ['E'] },
    { word: 'F', translations: ['Ef'] },
    { word: 'G', translations: ['Gue'] },
    { word: 'H', translations: ['Ja'] },
    { word: 'I', translations: ['I'] },
    { word: 'J', translations: ['Yot'] },
    { word: 'K', translations: ['K'] },
    { word: 'L', translations: ['El'] },
    { word: 'M', translations: ['Em'] },
    { word: 'N', translations: ['En'] },
    { word: 'O', translations: ['O'] },
    { word: 'P', translations: ['P'] },
    { word: 'Q', translations: ['Q'] },
    { word: 'R', translations: ['Er'] },
    { word: 'S', translations: ['Es'] },
    { word: 'T', translations: ['Ti'] },
    { word: 'U', translations: ['U'] },
    { word: 'V', translations: ['Fau'] },
    { word: 'W', translations: ['B'] },
    { word: 'X', translations: ['Ix'] },
    { word: 'Y', translations: ['Ypsilon/Üpsilon'] },
    { word: 'Z', translations: ['tset'] }
]

export const data = {
    Adverbs: adverbs,
    Alphabet: alphabet,
    "Dates and Time": dates,
    Domestic: domestic,
    "Jahreszeiten": seasons,
    Feelings: feelings,
    Frequency: frequency,
    Nature: nature,
    "New Palabros": newPalabros,
    Medicine: medicine,
    "Monate": months,
    "Predicative Adjectives": predicativeAdjectives,
    Prepositions: prepositions,
    Professions: professions,
    "Separable Verbs": separableVerbs,
    Variaety: variety,
    Verbs: verbs,
    Verbs2: verbs2,
    "Wochentage": weekDays,
}