// This should be on a .json
const verbs = [
    { word: 'abonnieren', translations: ['suscribir', 'abonar'] },
    { word: 'akzeptieren', translations: ['aceptar'] },
    { word: 'arbeiten', translations: ['trabajar'] },
    { word: 'benutzen', translations: ['usar', 'utilizar'] },
    { word: 'bestellen', translations: ['pedir'] },
    { word: 'bleiben', translations: ['quedarse', 'quedar'] },
    { word: 'der glaube', translations: ['la fe'] },
    { word: 'erkennen', translations: ['reconocer'] },
    { word: 'erlauben', translations: ['permitir'] },
    { word: 'ersetzen', translations: ['reemplazar', 'sustituir'] },
    { word: 'erweitern', translations: ['alargar', 'dilatar', 'ampliar', 'extender'] },
    { word: 'fahren', translations: ['viajar'] },
    { word: 'fehlen', translations: ['faltar', 'echar de menos'] },
    { word: 'finden', translations: ['encontrar'] },
    { word: 'funktionieren', translations: ['funcionar'] },
    { word: 'geben', translations: ['dar'] },
    { word: 'gefallen', translations: ['gustar'] },
    { word: 'glauben', translations: ['creer', 'opinar'] },
    { word: 'halten', translations: ['sostener', 'aguantar'] },
    { word: 'hoffen', translations: ['esperar', 'confiar'] },
    { word: 'hören', translations: ['oír', 'escuchar'] },
    { word: 'kochen', translations: ['cocinar'] },
    { word: 'kommen', translations: ['venir'] },
    { word: 'kosten', translations: ['costar', 'valer'] },
    { word: 'leben', translations: ['vivir'] },
    { word: 'liegen', translations: ['estar ubicado', 'estar tendido'] },
    { word: 'machen', translations: ['hacer'] },
    { word: 'meinen', translations: ['pensar', 'opinar'] },
    { word: 'möchten', translations: ['gusta'] },
    { word: 'nehmen', translations: ['tomar', 'coger'] },
    { word: 'passieren', translations: ['pasar', 'suceder', 'ocurrir'] },
    { word: 'prüfen', translations: ['revisar', 'controlar', 'probar'] },
    { word: 'reden', translations: ['hablar'] },
    { word: 'reisen', translations: ['viajar'] },
    { word: 'sammeln', translations: ['reunir', 'recoger', 'coleccionar'] },
    { word: 'scheinen', translations: ['brillar', 'parecer'] },
    { word: 'schließen', translations: ['cerrar'] },
    { word: 'schwimmen', translations: ['nadar'] },
    { word: 'singen', translations: ['cantar'] },
    { word: 'spazieren', translations: ['pasear'] },
    { word: 'stehlen', translations: ['robar'] },
    { word: 'stellen', translations: ['poner', 'colocar'] },
    { word: 'subskribieren', translations: ['suscribirse'] },
    { word: 'suchen', translations: ['buscar', 'rastrear'] },
    { word: 'treffen', translations: ['encontrar'] },
    { word: 'verbrauchen', translations: ['consumir'] },
    { word: 'verkaufen', translations: ['vender'] },
    { word: 'warten', translations: ['esperar'] },
    { word: 'wohnen', translations: ['vivir'] },
    { word: 'zeigen', translations: ['enseñar', 'mostrar', 'transmitir'] },
    { word: 'ändern', translations: ['cambiar', 'modificar'] },
    { word: 'übernehmen', translations: ['hacerse cargo de', 'tomar las riendas'] }
]

const separableVerbs = [
    { word: 'anhalten', translations: ['detener', 'parar'] },
    { word: 'anmachen', translations: ['encender'] },
    { word: 'aufhalten', translations: ['retener'] },
    { word: 'aufhören', translations: ['detener', 'terminar', 'acabar'] },
    { word: 'aufmachen', translations: ['abrir'] },
    { word: 'aufräumen', translations: ['limpiar'] },
    { word: 'aufstehen', translations: ['levantarse'] },
    { word: 'aufsteigen', translations: ['subir', 'montar'] },
    { word: 'ausgehen', translations: ['salir'] },
    { word: 'aussehen', translations: ['parecer'] },
    { word: 'aussteigen', translations: ['bajar', 'salir'] },
    { word: 'einsammeln', translations: ['recoger'] },
    { word: 'eintreffen', translations: ['llegar'] },
    { word: 'festhalten', translations: ['agarrar', 'detener'] },
    { word: 'hören auf', translations: ['hacer caso'] },
    { word: 'untergehen', translations: ['hundirse'] },
    { word: 'vorstellen', translations: ['presentar'] },
    { word: 'zumachen', translations: ['cerrar'] }
]

const predicativeAdjectives = [
    { word: 'abhängig', translations: ['adicto', 'dependiente'] },
    { word: 'aktiv', translations: ['activo'] },
    { word: 'allgemein', translations: ['general/mente', 'común'] },
    { word: 'ausgezeichnet', translations: ['excelente', 'magnífico'] },
    { word: 'automatisch', translations: ['automático'] },
    { word: 'begeister', translations: ['entusiasmado', 'impresionado'] },
    { word: 'beliebt', translations: ['apreciada', 'popular'] },
    { word: 'bereit', translations: ['listos'] },
    { word: 'deutlich', translations: ['claro', 'claramente'] },
    { word: 'echt', translations: ['de verdad', 'real', 'auténtico'] },
    { word: 'egal', translations: ['da lo mismo', 'igual', 'no importa'] },
    { word: 'eindeutig', translations: ['obvio', 'inequívoco', 'indiscutible', 'indudable'] },
    { word: 'erneut', translations: ['nuevo'] },
    { word: 'extrem', translations: ['extremadamente', 'extremo'] },
    { word: 'falsch', translations: ['malo', 'falso'] },
    { word: 'fertig', translations: ['cansado', 'rendido'] },
    { word: 'fit', translations: ['en forma'] },
    { word: 'herzlich', translations: ['cordial', 'afectuosa', 'cariñosa'] },
    { word: 'hilfreich', translations: ['útil', 'beneficioso'] },
    { word: 'höher', translations: ['más alto'] },
    { word: 'individuell', translations: ['individual'] },
    { word: 'international', translations: ['internacional'] },
    { word: 'jung', translations: ['joven'] },
    { word: 'jährlich', translations: ['anualmente', 'al año'] },
    { word: 'kaputt', translations: ['roto', 'estropeado'] },
    { word: 'knapp', translations: ['escasa', 'justa'] },
    { word: 'komplett', translations: ['completamente'] },
    { word: 'kürzlich', translations: ['recientemente', 'hace poco'] },
    { word: 'leicht', translations: ['ligero'] },
    { word: 'leichter', translations: ['más fácil', 'más liviano', 'más ligero'] },
    { word: 'länger', translations: ['más largo'] },
    { word: 'müde', translations: ['cansado'] },
    { word: 'notwendig', translations: ['necesaria'] },
    { word: 'offen', translations: ['abierto'] },
    { word: 'original', translations: ['original'] },
    { word: 'persönlich', translations: ['personal'] },
    { word: 'plötzlich', translations: ['de pronto', 'repentino'] },
    { word: 'privat', translations: ['en privado'] },
    { word: 'regional', translations: ['regional', 'local'] },
    { word: 'relativ', translations: ['relativo'] },
    { word: 'ruhig', translations: ['tranquilo'] },
    { word: 'schöner', translations: ['más bonito'] },
    { word: 'selbst', translations: ['por sí mismo'] },
    { word: 'selbstverständlich', translations: ['evidente', 'lógico', 'obvio'] },
    { word: 'sichtvar', translations: ['visible'] },
    { word: 'sinnvoll', translations: ['sensato'] },
    { word: 'stärker', translations: ['más fuertes'] },
    { word: 'tatsächlich', translations: ['efectivamente'] },
    { word: 'täglich', translations: ['diariamente', 'a diario'] },
    { word: 'unabhängig', translations: ['independiente'] },
    { word: 'unbekannt', translations: ['desconocido'] },
    { word: 'verantwortlich, zuständig', translations: ['responsable'] },
    { word: 'verfügbar', translations: ['disponible'] },
    { word: 'verpflichtet', translations: ['comprometido', 'obligado'] },
    { word: 'verständ', translations: ['comprensible'] },
    { word: 'völlig', translations: ['todo'] },
    { word: 'wert', translations: ['vale'] },
    { word: 'wesentlich', translations: ['esencial', 'fundamental'] },
    { word: 'wirklich', translations: ['de verdad', 'realmente'] },
    { word: 'zufrieden', translations: ['contento', 'satisfecho'] },
    { word: 'ähnlich', translations: ['similar', 'parecida', 'semejante'] }
]

const medicine = [
    { word: 'das auge', translations: ['el ojo'] },
    { word: 'das bein', translations: ['la pierna'] },
    { word: 'das blut', translations: ['la sangre'] },
    { word: 'das formular', translations: ['el formulario'] },
    { word: 'das gesicht', translations: ['la cara'] },
    { word: 'das haar', translations: ['el pelo'] },
    { word: 'das herz', translations: ['el corazón'] },
    { word: 'das krankenhaus', translations: ['el hospital'] },
    { word: 'das medikament', translations: ['el medicamento'] },
    { word: 'das opfer', translations: ['la víctima'] },
    { word: 'der Fuß', translations: ['el pie'] },
    { word: 'der alkohol', translations: ['el alcohol'] },
    { word: 'der finger', translations: ['el dedo'] },
    { word: 'der hals', translations: ['el cuello'] },
    { word: 'der kopf', translations: ['la cabeza'] },
    { word: 'der krankenwagen', translations: ['la ambulancia'] },
    { word: 'der körper', translations: ['el cuerpo'] },
    { word: 'der notfall', translations: ['la emergencia'] },
    { word: 'der patient', translations: ['el paciente'] },
    { word: 'der unfall', translations: ['el accidente'] },
    { word: 'die beine', translations: ['las piernas'] },
    { word: 'die diät', translations: ['la dieta'] },
    { word: 'die ernährung', translations: ['la alimentación'] },
    { word: 'die füße', translations: ['los pies'] },
    { word: 'die geburt', translations: ['el nacimiento', 'parto'] },
    { word: 'die gesundheit', translations: ['la salud'] },
    { word: 'die haare', translations: ['el pelo'] },
    { word: 'die hand', translations: ['la mano'] },
    { word: 'die haut', translations: ['la piel'] },
    { word: 'die klinik', translations: ['la clínica'] },
    { word: 'die krankenversicherung', translations: ['el seguro de enfermedad'] },
    { word: 'die krankheit', translations: ['la enfermedad'] },
    { word: 'die medizin', translations: ['la medicina'] },
    { word: 'die pflege', translations: ['el cuidado', 'la asistencia'] },
    { word: 'die praxis', translations: ['el consultorio'] },
    { word: 'die sucht', translations: ['la adicción'] },
    { word: 'die therapie', translations: ['la terapia'] },
    { word: 'die untersuchung', translations: ['el examen', 'análisis', 'chequeo'] },
    { word: 'krank', translations: ['enfermo'] }
]

const newPalabros = [
    { word: 'apotheke', translations: ['farmacia'] },
    { word: 'auch', translations: ['también'] },
    { word: 'computer', translations: ['computadora'] },
    { word: 'da', translations: ['allí'] },
    { word: 'das fenster ist auf', translations: ['la ventana está abierta'] },
    { word: 'das fußballspieler', translations: ['el futbolista'] },
    { word: 'das meer', translations: ['el océano'] },
    { word: 'das mädchen ist draußen', translations: ['la niña está fuera'] },
    { word: 'das problem', translations: ['el problema'] },
    { word: 'das wetter', translations: ['el tiempo'] },
    { word: 'der aufzug ist da vorne', translations: ['el ascensor está ahí enfrente'] },
    { word: 'der berg', translations: ['la montaña'] },
    { word: 'der druck', translations: ['la presión'] },
    { word: 'der junge ist drinnen', translations: ['el niño está dentro'] },
    { word: 'der karton ist leer', translations: ['la caja está vacía'] },
    { word: 'der külhschrank', translations: ['el frigorífico'] },
    { word: 'der politiker', translations: ['el político'] },
    { word: 'der preis', translations: ['el precio'] },
    { word: 'der schrank', translations: ['el armario'] },
    { word: 'der sommer', translations: ['el verano'] },
    { word: 'der sport', translations: ['el deporte'] },
    { word: 'die bäckerei', translations: ['la panadería'] },
    { word: 'die freiheit', translations: ['la libertad'] },
    { word: 'die kinder sind weg', translations: ['los niños se han ido'] },
    { word: 'die lampe ist aus', translations: ['la lámpara está apagada'] },
    { word: 'die nachrichten', translations: ['las noticias'] },
    { word: 'die prüfung', translations: ['el examen'] },
    { word: 'die ratte', translations: ['la rata'] },
    { word: 'die sprache', translations: ['el lenguaje'] },
    { word: 'die treppe ist da hinten', translations: ['las escaleras están allí detrás'] },
    { word: 'die tür ist zu', translations: ['la puerta está cerrada'] },
    { word: 'die wahrheit', translations: ['la verdad'] },
    { word: 'dort', translations: ['allí'] },
    { word: 'draußen', translations: ['fuera'] },
    { word: 'er lernt viel', translations: ['él estudia mucho'] },
    { word: 'erklären', translations: ['explicar'] },
    { word: 'erwarten', translations: ['esperar'] },
    { word: 'gefährlich', translations: ['peligroso'] },
    { word: 'gerade', translations: ['ahora'] },
    { word: 'geradeus', translations: ['recto'] },
    { word: 'guten abend', translations: ['buenas tardes'] },
    { word: 'guten morgen', translations: ['buenos días'] },
    { word: 'guten tag', translations: ['buen día'] },
    { word: 'hier', translations: ['aquí'] },
    { word: 'ich heiße', translations: ['me llamo'] },
    { word: 'ich komme aus', translations: ['vengo de'] },
    { word: 'ich wohne in', translations: ['vivo en'] },
    { word: 'kritisieren', translations: ['criticar'] },
    { word: 'lernen', translations: ['estudiar', 'aprender'] },
    { word: 'lärm', translations: ['ruido'] },
    { word: 'oben', translations: ['arriba'] },
    { word: 'pause', translations: ['descanso'] },
    { word: 'prima', translations: ['bien'] },
    { word: 'rechts', translations: ['derechos'] },
    { word: 'schreien', translations: ['gritar'] },
    { word: 'studieren', translations: ['estudiar'] },
    { word: 'unten', translations: ['debajo'] },
    { word: 'verlieren', translations: ['perder'] },
    { word: 'vielleicht', translations: ['quizás'] },
    { word: 'wie heißen sie?', translations: ['cómo se llama? formal'] },
    { word: 'wie heißt du?', translations: ['cómo te llamas? informal'] },
    { word: 'wie heißt ihr?', translations: ['cómo os llamais? informal'] },
    { word: 'wie ist dein name?', translations: ['cuál es tu nombre? informal'] },
    { word: 'wie ist ihr name?', translations: ['cuál es su nombre? formal'] },
    { word: 'überstunden', translations: ['horas extra'] }
]

const separateWordAndTranslations = (data) => {
    return {
        words: data.map(row => row.word),
        translations: data.map(row => row.translations)
    }
}

export const data = {
    Verbs: separateWordAndTranslations(verbs),
    SeparableVerbs: separateWordAndTranslations(separableVerbs),
    PredicativeAdjectives: separateWordAndTranslations(predicativeAdjectives),
    Medicine: separateWordAndTranslations(medicine),
    NewPalabros: separateWordAndTranslations(newPalabros),
}

// Bad practice to loop two times the same array
export const mockedDictionary = {
    words: verbs.map(row => row.word),
    translations: verbs.map(row => row.translations)
}